import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { ThemeProvider } from "@/components/theme-provider";
// import { Toaster } from "@repo/ui/sonner";
import "./globals.css";
import { Navbar } from "@/components/navbar";
import { getVerifiedToken } from "@/lib/cookie";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  // TODO: FIX THE COOKIE js-cookie module error
  const isLoggedIn = await getVerifiedToken();
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <ThemeProvider defaultTheme="light" storageKey="draw-meetings-theme">
          <div className="w-full bg-gray-50 dark:bg-gray-950">
            <Navbar isLoggedIn={!!isLoggedIn}/>
            {children}
            {/* <Toaster/> */}
          </div>
        </ThemeProvider>
      </body>
    </html>
  );
}
